@TestBE_HostAddress = http://localhost:5197

GET {{TestBE_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{TestBE_HostAddress}}/api/product?pagesize=10&pageindex=1
Accept: application/json

###
GET {{TestBE_HostAddress}}/api/common/shop-info?domain=1
Accept: application/json

###
GET {{TestBE_HostAddress}}/api/product/get-from-shopify?pagesize=10&pageindex=1&domain=codonqua.myshopify.com
Accept: application/json